CREATE TABLE IF NOT EXISTS usuarios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'operador',
    activo TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pabellones (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    imagen VARCHAR(255) NULL,
    ancho INT NOT NULL DEFAULT 1200,
    alto INT NOT NULL DEFAULT 800,
    orden INT NOT NULL DEFAULT 0,
    activo TINYINT NOT NULL DEFAULT 1,
    area_x DECIMAL(10,3) NULL,
    area_y DECIMAL(10,3) NULL,
    area_ancho DECIMAL(10,3) NULL,
    area_alto DECIMAL(10,3) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS configuracion (
    clave VARCHAR(80) PRIMARY KEY,
    valor TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stands (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pabellon_id INT UNSIGNED NULL,
    clave VARCHAR(40) NOT NULL UNIQUE,
    numero VARCHAR(40) NOT NULL,
    categoria VARCHAR(40) NOT NULL DEFAULT 'Premium',
    estado VARCHAR(20) NOT NULL DEFAULT 'Disponible',
    empresa VARCHAR(160) NULL,
    logo VARCHAR(255) NULL,
    contacto VARCHAR(160) NULL,
    email VARCHAR(160) NULL,
    telefono VARCHAR(60) NULL,
    x DECIMAL(10,3) NULL,
    y DECIMAL(10,3) NULL,
    ancho DECIMAL(10,3) NULL,
    alto DECIMAL(10,3) NULL,
    bloqueado TINYINT NOT NULL DEFAULT 0,
    INDEX idx_pabellon (pabellon_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO configuracion (clave, valor)
VALUES ('mapa_areas', 'IMG/Areas.png');
